image: maven:latest

stages:
  - build
  - test
  - run

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

run:
  stage: run
  script:
    - mvn package
    - mvn exec:java -Dexec.mainClass="com.goosegame.GooseGameApplication"